import { Inter } from "next/font/google";
import Head from 'next/head';
import Header from './components/header';

//import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

{/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/}

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>Meus TCCs</title>
        <meta name="Descrição" content="Descrição da sua página aqui" />
      </Head>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </>
  );
}
