import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

/*
TODO: Verificar o motivo da Vercel não reconhecer o export const metadata
Durante tentativa de deploy estava retornando o problema: 
Error exporting ‘metadata’ from a component marked with ‘use client’ during Vercel deployment
*/
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
